[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "metadata_poc"
description = "PoC for metadata bug"
license = {file = "license.txt"}
version = "0.0.1"
dependencies = [
     "requests",
]
